In [69]:
import numpy as np

In [70]:
# Question - 1

import random

np_arr = np.random.randint(1,21,size = (5,5))
np_arr[:,2] = 1
print(np_arr)

np_arr2 = np.random.randint(1,17,size = (4,4))
np.fill_diagonal(np_arr2,0)
print(np_arr2)

[[16 13  1  8 14]
 [13 12  1 10 17]
 [18 14  1 14 11]
 [17  4  1  9 10]
 [ 1  3  1  5 20]]
[[ 0 14  2 12]
 [ 4  0 10 14]
 [ 9  3  0  6]
 [ 6  1  1  0]]


In [71]:
# Question - 2

np_arr = np.arange(1,37).reshape(6,6)
print(np_arr[2:5,2:4])

np_arr2 = np.random.rand(5,5)
print(np_arr2[0::4,0::4])


[[15 16]
 [21 22]
 [27 28]]
[[0.15633169 0.02394137]
 [0.82402934 0.45956264]]


In [72]:
# Question - 3

np_arr = np.random.randint(1,10,(3,4))
np_arr2 = np.random.randint(1,20,(3,4))

print(np_arr)
print(np_arr2)

print(np_arr + np_arr2)
print(np_arr - np_arr2)
print(np_arr * np_arr2)
print(np_arr / np_arr2)

np_arr3 = np.arange(1,17).reshape(4,4)
print(np_arr3)
print(np.sum(np_arr3,axis = 1))
print(np.sum(np_arr3,axis = 0))


[[3 4 5 6]
 [1 9 8 9]
 [6 4 7 6]]
[[ 7  3  3 10]
 [16  7 18  9]
 [19 10  6 19]]
[[10  7  8 16]
 [17 16 26 18]
 [25 14 13 25]]
[[ -4   1   2  -4]
 [-15   2 -10   0]
 [-13  -6   1 -13]]
[[ 21  12  15  60]
 [ 16  63 144  81]
 [114  40  42 114]]
[[0.42857143 1.33333333 1.66666667 0.6       ]
 [0.0625     1.28571429 0.44444444 1.        ]
 [0.31578947 0.4        1.16666667 0.31578947]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [91]:
# Question - 4

np_arr = np.random.randint(1,40,size = (5,5))
print(np.mean(np_arr))
print(np.median(np_arr))
print(np.std(np_arr))
print(np.var(np_arr))


np_arr4 = np.random.randint(1,9,size = (3,3))
print(np_arr4)
normalized_np_arr4 = (np_arr4 - np.mean(np_arr4)) / np.std(np_arr4)
print(normalized_np_arr4)

20.56
20.0
9.621143383195161
92.56640000000002
[[2 2 2]
 [6 5 4]
 [7 5 3]]
[[-1.13389342 -1.13389342 -1.13389342]
 [ 1.13389342  0.56694671  0.        ]
 [ 1.70084013  0.56694671 -0.56694671]]


In [96]:
# Question - 5

np_arr = np.random.randint(1,10,size = (3,3))
np_1_d_arr = np.random.randint(1,5,size = (3))
print(np_arr)
print(np_1_d_arr)
print(np_arr+np_1_d_arr)


# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

[[6 5 7]
 [1 8 1]
 [9 4 4]]
[3 3 4]
[[ 9  8 11]
 [ 4 11  5]
 [12  7  8]]
Original array:
[[ 9  4  6  8]
 [10  7  6  7]
 [ 2  1  7  7]
 [ 3 10  4  4]]
1D array:
[2 8 9 5]
Resulting array:
[[ 7  2  4  6]
 [ 2 -1 -2 -1]
 [-7 -8 -2 -2]
 [-2  5 -1 -1]]


In [103]:
# Question - 6

np_arr = np.random.randint(1,10,size=(3,3))

# We use the np.linalg module to do linear algebra

print(np.linalg.det(np_arr))
print(np.linalg.inv(np_arr))
print()
print(np.linalg.eigvals(np_arr))

np_arr2 = np.random.randint(1,10,size=(2,3))
np_arr3 = np.random.randint(1,10,size=(3,2))

np.matmul(np_arr2,np_arr3)


-15.999999999999998
[[-0.1875 -0.5625  0.6875]
 [-0.25    2.25   -1.75  ]
 [ 0.1875 -0.4375  0.3125]]

[15.40005859 -2.77452204  0.37446345]


array([[48, 52],
       [38, 64]])

In [105]:
# Question - 7

# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Original array:
[[10  2 12 13  4]
 [19 18 17  9 19]
 [ 3 18  2  5  8]
 [10 20 15 15  3]
 [13  9 18  7 10]]
Flattened array:
[10  2 12 13  4 19 18 17  9 19  3 18  2  5  8 10 20 15 15  3 13  9 18  7
 10]
Reshaped array:
[[10  2 12 13  4]
 [19 18 17  9 19]
 [ 3 18  2  5  8]
 [10 20 15 15  3]
 [13  9 18  7 10]]


In [ ]:
# Question - 8
