In [28]:
import numpy as np

In [29]:
# Question - 1

import random

np_arr = np.random.randint(1,21,size = (5,5))
np_arr[:,2] = 1
print(np_arr)

np_arr2 = np.random.randint(1,17,size = (4,4))
np.fill_diagonal(np_arr2,0)
print(np_arr2)

[[ 7 17  1  4 14]
 [19 12  1  6 11]
 [12 12  1 20 17]
 [ 3  5  1 18 18]
 [18  1  1  3  2]]
[[ 0  7 11 13]
 [ 3  0 12  2]
 [15 13  0  8]
 [ 9  1  6  0]]


In [45]:
# Question - 2

np_arr = np.arange(1,37).reshape(6,6)
print(np_arr[2:5,2:4])

np_arr2 = np.random.rand(5,5)
print(np_arr2[0::4,0::4])


[[15 16]
 [21 22]
 [27 28]]
[[0.64972509 0.72695041]
 [0.15805732 0.73329969]]


In [ ]:
# Question - 3
