In [1]:
! pip install numpy

In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
# Used for reshaping

arr2 = np.reshape(arr1,(1,5))
print(arr2)

[[1 2 3 4 5]]


In [10]:
arr3 = np.arange(0,10).reshape(2,5)
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
arr4 = np.ones((2,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# FOr creating an identity matrix we use np.eye(I)

arr5 = np.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr6 = np.array([1,2,3,4,5])
arr7 = np.array([7,8,9,10,100])

print(arr6+arr7)
print(arr6-arr7)
print(arr6*arr7)
print(arr6/arr7)

[  8  10  12  14 105]
[ -6  -6  -6  -6 -95]
[  7  16  27  40 500]
[0.14285714 0.25       0.33333333 0.4        0.05      ]


In [29]:
# Array Indexing And Slicing

arr8 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

# print(arr8)

print(arr8[2][3])
print(arr8[1:,2:])



14
[[ 8  9 10]
 [13 14 15]]


In [33]:
# Modifying all values in an array
arr8[0][0] = 200
arr8[1:] = 100
print(arr8)

[[200   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [40]:
# Logical Operations

arr10 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

arr10[(arr10 > 5) & (arr10 < 10)]

array([6, 7, 8, 9])